
import Head from 'next/head'
// import LayoutNotApp from 'src/views/layouts/layoutNotApp'

const Index = () => {

  return (
    <>
      <Head>
        <title>HT test </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>


    </>
  )
}
export default Index

// ManageSystem.getLayout = (page: React.ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
//Index.gusetGuard = true