'use client'
import Head from 'next/head'
import LayoutNotApp from 'src/views/layouts/layoutNotApp'

const Home = () => {

  return (
    <>
      <Head>
        <title>HT test </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>


    </>
  )
}
export default Home

Home.getLayout = (page: React.ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
Home.gussetGuard = false;
Home.authGuard = false;